// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIsLbVjAATFqryZ2x30PCuII0qfPd3V5o',
    appId: '1:66012018687:web:d4b09b9051a4f53be059ca',
    messagingSenderId: '66012018687',
    projectId: 'login-4eebb',
    authDomain: 'login-4eebb.firebaseapp.com',
    storageBucket: 'login-4eebb.appspot.com',
    measurementId: 'G-78G2HF1YV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY2YJSdOzunFx2JaJqdxONLcTHoYSsXNU',
    appId: '1:66012018687:android:c33378940f612479e059ca',
    messagingSenderId: '66012018687',
    projectId: 'login-4eebb',
    storageBucket: 'login-4eebb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn-tL5I-P3JZuSqvaTgKDWxLxPdXm-Yog',
    appId: '1:66012018687:ios:e25630dcd0afec78e059ca',
    messagingSenderId: '66012018687',
    projectId: 'login-4eebb',
    storageBucket: 'login-4eebb.appspot.com',
    iosClientId: '66012018687-e2miudqpjm9jvotgifghekm37f5k8ier.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn-tL5I-P3JZuSqvaTgKDWxLxPdXm-Yog',
    appId: '1:66012018687:ios:e9fddeb763d3c971e059ca',
    messagingSenderId: '66012018687',
    projectId: 'login-4eebb',
    storageBucket: 'login-4eebb.appspot.com',
    iosClientId: '66012018687-hvdlug62kpbv5hblcm0umbvgrj7o1k9k.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen.mac',
  );
}
